version: "3.6"
services:
  front-end:
    build:
      context: ./front-end
    image: ${DOCKER_REGISTRY:-localhost}/front-end
    ports:
      - 80:8010
    volumes:
      - ./front-end:/src/
      - nodemodules:/src/node_modules
    environment:
      HOST: "0.0.0.0"
      PORT: "8010"
      GATEWAY_PORT: "8080"
    networks:
      microservice:
networks:
  accountsNetwork:
  submissionHistory:
  microservice:  
volumes:
  mongo_accounts_data:
  submissionHistoryData: